#!/bin/bash

echo "Removing old links..."
rm -fr ~/.vimrc
rm -fr ~/.zshrc
rm -fr ~/.tmux.conf

echo "Creating symbolic links to dotfiles"
cd ~
ln -s .dot-files/.vimrc ~/.vimrc
ln -s .dot-files/.zshrc ~/.zshrc
ln -s .dot-files/.tmux.conf ~/.tmux.conf
