#!/bin/bash

if [[ ! -d "$HOME/.jenv" ]]; then
  echo "Installing jenv..."
  curl -L -s get.jenv.io | bash
fi

if [[ ! -d "$HOME/.rvm" ]]; then
 echo "Installing rvm..."
 gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
 curl -sSL https://get.rvm.io | bash -s stable
fi

if [[ ! -d "$HOME/.nvm" ]]; then
 echo "Installing nvm..."
 curl https://raw.githubusercontent.com/creationix/nvm/v0.29.0/install.sh | bash
fi

echo "Installing tools..."
sudo apt-get -y install git tmux zsh vim imagemagick &>/dev/null
echo "Installing i3 & tools..."
sudo apt-get -y install i3 xautolock scrot &>/dev/null

if [[ ! -d "$HOME/.oh-my-zsh" ]]; then
 echo "Installing Oh-My-Zsh..."
 sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" &>/dev/null
fi

if [[ ! -d "$HOME/.vim/bundle/Vundle.vim" ]]; then
 echo "Installing Vundle..."
 git clone https://github.com/VundleVim/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim &>/dev/null
fi

echo "Installing Powerline Fonts"
rm -fr /tmp/powerline-fonts > /dev/null
mkdir -p /tmp/powerline-fonts
git clone https://github.com/powerline/fonts.git /tmp/powerline-fonts &>/dev/null
/tmp/powerline-fonts/install.sh

echo "Installing Font-awesome"
rm -fr /tmp/font-awesome > /dev/null
mkdir -p /tmp/font-awesome
wget -P /tmp http://fontawesome.io/assets/font-awesome-4.5.0.zip
unzip /tmp/font-awesome-4.5.0.zip -d /tmp
cp /tmp/font-awesome-4.5.0/fonts/fontawesome-webfont.ttf $HOME/.fonts

echo "Removing old links..."
rm -fr $HOME/.vimrc
rm -fr $HOME/.zshrc
rm -fr $HOME/.tmux.conf
rm -fr $HOME/.i3
rm -fr $HOME/.i3status.conf
sudo rm -fr /usr/local/bin/lock_screen

echo "Creating symbolic links to dotfiles"
cd $HOME
mkdir $HOME/.i3
ln -s $HOME/.dot-files/.vimrc $HOME/.vimrc
ln -s $HOME/.dot-files/.zshrc $HOME/.zshrc
ln -s $HOME/.dot-files/.tmux.conf $HOME/.tmux.conf
ln -s $HOME/.dot-files/i3/config $HOME/.i3/config
ln -s $HOME/.dot-files/i3/i3status.conf $HOME/.i3status.conf
sudo ln -s $HOME/.dot-files/i3/scripts/lock_screen /usr/local/bin/lock_screen
