#!/bin/bash

if [[ ! -d "$HOME/.jenv" ]]; then
  echo "Installing jenv..."
  curl -L -s get.jenv.io | bash
fi

if [[ ! -d "$HOME/.rvm" ]]; then
 echo "Installing rvm..."
 gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
 curl -sSL https://get.rvm.io | bash -s stable
fi

if [[ ! -d "$HOME/.rvm" ]]; then
 echo "Installing nvm..."
 curl https://raw.githubusercontent.com/creationix/nvm/v0.25.1/install.sh | bash
fi

echo "Installing tmux..."
sudo apt-get install tmux
echo "Installing zsh..."
sudo apt-get install zsh
echo "Installing vim"
sudo apt-get install vim

if [[ ! -d "$HOME/.jenv" ]]; then
 echo "Installing jenv..."
 curl -L -s get.jenv.io | bash
fi

if [[ ! -d "$HOME/.vim/bundle/Vundle.vim" ]]; then
 echo "Installing Vundle..."
 git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi

echo "Removing old links..."
rm -fr ~/.vimrc
rm -fr ~/.zshrc
rm -fr ~/.tmux.conf

echo "Creating symbolic links to dotfiles"
cd ~
ln -s .dot-files/.vimrc ~/.vimrc
ln -s .dot-files/.zshrc ~/.zshrc
ln -s .dot-files/.tmux.conf ~/.tmux.conf
